# Generated by Django 2.2.6 on 2019-10-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар(В заказе)', 'verbose_name_plural': 'Товары(В Заказах)'},
        ),
    ]
