# Generated by Django 2.2.6 on 2019-11-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productinbasket_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'verbose_name': 'Товар(В Корзине)', 'verbose_name_plural': 'Товары(В Корзинах)'},
        ),
    ]
